# Generated by Django 4.2.7 on 2024-10-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("node_id", models.CharField(max_length=100, unique=True, verbose_name="节点ID")),
                ("action", models.JSONField(default=list, verbose_name="操作")),
            ],
            options={
                "verbose_name": "操作信息",
                "db_table": "action",
            },
        ),
        migrations.CreateModel(
            name="Collector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("collector_id", models.CharField(max_length=100, unique=True, verbose_name="采集器ID")),
                ("collector_name", models.CharField(max_length=100, verbose_name="采集器名称")),
                ("service_type", models.CharField(max_length=100, verbose_name="服务类型")),
                ("operating_system", models.CharField(default="", max_length=50, verbose_name="操作系统类型")),
                ("executable_path", models.CharField(max_length=200, verbose_name="可执行文件路径")),
                ("execute_parameters", models.CharField(max_length=200, verbose_name="执行参数")),
                ("validation_parameters", models.CharField(max_length=200, verbose_name="验证参数")),
            ],
            options={
                "verbose_name": "采集器信息",
                "db_table": "collector",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("node_id", models.CharField(max_length=100, unique=True, verbose_name="节点ID")),
                ("node_name", models.CharField(max_length=100, verbose_name="节点名称")),
                ("ip", models.CharField(max_length=30, verbose_name="IP地址")),
                ("operating_system", models.CharField(default="", max_length=50, verbose_name="操作系统类型")),
                ("collector_configuration_directory", models.CharField(max_length=200, verbose_name="采集器配置目录")),
                ("metrics", models.JSONField(default=dict, verbose_name="指标")),
                ("status", models.JSONField(default=dict, verbose_name="状态")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("log_file_list", models.JSONField(default=list, verbose_name="日志文件列表")),
            ],
            options={
                "verbose_name": "节点信息",
                "db_table": "node",
            },
        ),
        migrations.CreateModel(
            name="NodeCollectorConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("node_id", models.CharField(max_length=100, verbose_name="节点ID")),
                ("collector_id", models.CharField(max_length=100, verbose_name="采集器ID")),
                ("config_id", models.CharField(max_length=100, verbose_name="配置ID")),
            ],
            options={
                "verbose_name": "节点采集器配置信息",
                "db_table": "node_collector_configuration",
            },
        ),
        migrations.CreateModel(
            name="CollectorConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("config_id", models.CharField(max_length=100, unique=True, verbose_name="配置ID")),
                ("config_name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("config_template", models.TextField(verbose_name="配置模板")),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="node_mgmt.collector", verbose_name="采集器"
                    ),
                ),
            ],
            options={
                "verbose_name": "采集器配信息",
                "db_table": "collector_configuration",
            },
        ),
    ]
